version: '3.9'
services:
  # backend:
  #   build: .
  #   ports:
  #     - 8000:3000
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db

  ambassador_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  ambassador_adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    depends_on:
      - ambassador_db
